name: simple_tv
description: "Simple TV"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  better_player: ^0.0.83
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^8.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.9
  go_router: ^13.2.4
  injectable: ^2.3.5
  json_annotation: ^4.8.1
  logger: ^2.2.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^3.2.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  pedantic_mono: ^1.26.0
  retrofit_generator: ^8.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icons/logo.png"